update ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -72,20 +72,33 @@ jobs:
             docker compose pull
             docker compose up -d
 
-      - name: Deploy Health Check
-        run: |
-          echo "Waiting for services to start..."
-          sleep 10
-          curl -f http://michel.dev.noseryoung.ch:8922 || (echo "Frontend is down" && exit 1)
-          curl -f -X POST http://michel.dev.noseryoung.ch:8923/api/user/login \
-            -H "Content-Type: application/json" \
-            -d '{"email": "user@example.com", "password": "1234"}' || (echo "Backend login failed" && exit 1)
+  health-check:
+    runs-on: ubuntu-latest
+    needs: deploy
+    steps:
+      - name: Remote Health Check
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.USERNAME }}
+          password: ${{ secrets.PASSWORD }}
+          port: 2222
+          script: |
+            echo "Waiting for services to start..."
+            sleep 10
+            curl -f http://localhost:8922 || (echo "Frontend is down" && exit 1)
+            curl -f -X POST http://localhost:8923/api/user/login \
+              -H "Content-Type: application/json" \
+              -d '{"email": "user@example.com", "password": "1234"}' || (echo "Backend login failed" && exit 1)
+
 
 
   message:
     runs-on: ubuntu-latest
-    needs: deploy
+    needs: health-check
+    if: always()
     steps:
+
     - name: Discord Webhook Action
       uses: tsickert/discord-webhook@v7.0.0
       with:
